on:
  push:
    branches:
      - main
      - topic/*

  pull_request:

name: AOCLang CI

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo test --verbose --all

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup component add rustfmt
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup component add clippy
      - run: cargo clippy --all-features

  # wasm:
  #   name: Wasm-pack
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: jetli/wasm-pack-action@v0.4.0
  #     - run: wasm-pack build --target no-modules --release --out-dir pkg
  #     - run: rm pkg/.gitignore
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: wasm-pkg
  #         path: 2022/pkg


  # deploy:
  #   name: Deploy github pages
  #   runs-on: ubuntu-latest
  #   needs: [check, test, fmt, clippy, wasm]
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: wasm-pkg
  #         path: 2022/pkg
  #     - uses: JamesIves/github-pages-deploy-action@v4
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         branch: gh-pages
  #         folder: 2022
  #         target-folder: 2022
  #         clean: true
